<?php
// $Id$

/**
 * Implementation of hook_autoload_info().
 */
function dissue_autoload_info() {
  return array(
    'DIssue' => array(
      'file' => 'includes/DIssue.php',
    ),
    'DIssueHooks' => array(
      'file' => 'includes/DIssueHooks.php',
    ),
  );
}

/**
 * @see DIssueHooks::theme().
 */
function dissue_theme() {
  return DIssueHooks::theme();
}

/**
 * @see DIssueHooks::perm().
 */
function dissue_perm() {
  return DIssueHooks::perm();
}

/**
 * @see DIssueHooks::menu().
 */
function dissue_menu() {
  return DIssueHooks::menu();
}